/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 */


plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
    
}


rootProject.name = "s2425v-leic42d"
include("lecture-02-18-threds-intro")
include("lecture-02-18-threads-intro")
include("lecture-02-19-concurrency-intro")
include("lab1")
include("lecture-02-25-data-synchronization")
include("lecture-03-05-control-synchronization-intro")
include("lab2")
include("lecture-03-11-control-synchronization")
include("lecture-03-12-monitors-intro")
include("lecture-03-18-more-monitors")
include("lecture-03-19-kernel-style-intro")
include("lecture-03-25-26-kernel-style-2")
include("lecture-04-01-broadcast-server-intro")
include("lecture-04-01-broadcast-server-intro")
include("lecture-04-02-memory-model-and-async-intro")
include("lecture-04-08-09-async-programming-without-threads-intro")
include("lecture-04-15-coroutines-core")

include("lecture-04-29-more-about-coroutines")
include("lecture-05-06-asynchronizers")
include("lecture-05-07-09-nio-coroutinesx")

include("lecture-05-20-structured-concurrency")